# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_id=ifwootaddon
mod_name=Industrial Foregoing: Woot Addon
mod_version=1.0.1

# Platform Properties
java_version=17
mc_version=1.20.1
neo_version=47.1.106

# Dependency Properties
jei_version=15.20.0.100
jade_version=11.9.1+forge
woot_version=1.1.0
guideme_version=20.1.7
if_version=1.20.1-3.5.8
titanium_version=1.20.1-3.8.32

# Optimization Mods
embeddium_version=0.3.32-beta.58+mc1.20.1
modernfix_version=5.24.4+mc1.20.1-forge
ferritecore_version=6.0.1-forge